export const GENERIC_LABELS = [
  "color",
  "icon_color",
  "layout",
  "fill_container",
  "primary_info",
  "secondary_info",
  "max_width",
  "icon_type",
  "icon_background",
  "content_info",
  "use_entity_picture",
  "collapsible_controls",
  "icon_animation",
];
